- name: Configuración por departamento
  hosts: departamentos
  become: yes

  tasks:

    - name: Instalar herramientas para DEP1
      apt:
        name:
          - paquete
          - paquete
        state: present
      when: "'dep1' in group_names"

    - name: Instalar herramientas para DEP2
      apt:
        name:
          - paquete
          - paquete
        state: present
      when: "'dep2' in group_names"

    - name: Instalar herramientas para DEP3
      apt:
        name:
          - paquete
          - paquete
        state: present
      when: "'dep3' in group_names"
